public enum Notifications
{
    TILES_COLORED,
    LEVEL_COMPLETE,
    CATEGORY_UNLOCKED,
    LINE_COMPLETED,
    BOARD_COMPLETE,
    POWERUP_USED,
    PAUSE_GAME,
    UNPAUSE_GAME,
    ITEM_PURCHASED,
    OBJECTIVE_REWARD_CLAIMED,
    OBJECTIVE_COMPLETE,
    SEGMENTS_RECEIVED,
    EXP_RECEIVED,
    POWERUP_RECEIVED,
    REWARD_CHEST_OPENED
}